### ISSUE TITLE
FlutterMainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.plugin.common.BinaryMessenger io.flutter.embedding.engine.plugins.FlutterPlugin$FlutterPluginBinding.getBinaryMessenger()' on a null object reference

### ISSUE THREAD

**Issue by hlovingness** [yuewen/mix_stack#10]
```
io.flutter.embedding.engine.plugins.FlutterPlugin$FlutterPluginBinding.getBinaryMessenger()' on a null object reference
E/CrashReport(20510): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4545)
E/CrashReport(20510): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4577)
E/CrashReport(20510): 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
E/CrashReport(20510): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
E/CrashReport(20510): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/CrashReport(20510): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2142)
E/CrashReport(20510): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/CrashReport(20510): 	at android.os.Looper.loop(Looper.java:236)
E/CrashReport(20510): 	at android.app.ActivityThread.main(ActivityThread.java:7864)
E/CrashReport(20510): 	at java.lang.reflect.Method.invoke(Native Method)
E/CrashReport(20510): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
E/CrashReport(20510): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
E/CrashReport(20510): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.plugin.common.BinaryMessenger io.flutter.embedding.engine.plugins.FlutterPlugin$FlutterPluginBinding.getBinaryMessenger()' on a null object reference
E/CrashReport(20510): 	at com.crazecoder.openfile.OpenFilePlugin.onAttachedToActivity(OpenFilePlugin.java:400)
E/CrashReport(20510): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.attachToActivityInternal(FlutterEngineConnectionRegistry.java:351)
E/CrashReport(20510): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.attachToActivity(FlutterEngineConnectionRegistry.java:324)
E/CrashReport(20510): 	at com.yuewen.mix_stack.component.ActivityFragmentDelegate.onAttach(ActivityFragmentDelegate.java:106)
E/CrashReport(20510): 	at com.yuewen.mix_stack.component.MXFlutterActivity.onResume(MXFlutterActivity.java:102)
E/CrashReport(20510): 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
E/CrashReport(20510): 	at android.app.Activity.performResume(Activity.java:8264)
E/CrashReport(20510): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4535)
E/CrashReport(20510): 	... 11 more
```

**Comment by pepsin** [comment]
Which Flutter version are you using?

**Comment by hlovingness** [comment]
> Which Flutter version are you using?

Flutter (Channel stable, 3.3.5, on Microsoft Window

**Comment by hlovingness** [comment]
运行demo没有问题，但是原模原样集成到我的项目中就会报这个错
